add_newline = false

format = """

[ î‚²](fg:blue)\
[ $directory ](fg:black bg:blue)\
[î‚°](fg:blue bg:14)\
[$jobs](bg:14 fg:black)\
[î‚°](fg:14 bg:13)\
[\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
](fg:black bg:13)\
[î‚°](fg:13 bg:11)\
[$git_branch$git_status](bg:11 fg:black)\
[î‚°](fg:11 bg:8)\
[ $time](bg:8 fg:15)\
$character\
$fill\
$cmd_duration 
   [~ ](fg:14)
"""

continuation_prompt = "   [~ ](fg:14)"

[profiles]
short = """
[ î‚²](fg:blue)\
[ $directory ](bg:blue fg:black)\
[î‚°](fg:blue bg:8)\
[ $time](fg:15 bg:8)\
$character
"""

multi_short = """

[ î‚²](fg:blue)\
[ $directory ](bg:blue fg:black)\
[î‚°](fg:blue bg:8)\
[ $time](fg:15 bg:8)\
$character
   [~ ](fg:14)
"""

rshort = "$cmd_duration"

[character]
success_symbol = "[ ](bg:8)[î‚°](fg:8)"
error_symbol = "[î‚°](fg:8 bg:red)[î‚°](fg:red)"

[directory]
format = "$path"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "ğŸŒ±/"
home_symbol = "ğŸ¡"

[directory.substitutions]
"/workspaces" = " / ğŸŒº "

[c]
symbol = "î˜ "
format = ' $symbol ($version) '

[cmd_duration]
format = """
[î‚²](fg:15)\
[$duration](bg:15 fg:0)\
[î‚°](fg:15)\
"""

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[fill]
symbol = ' '

[git_branch]
symbol = "îœ¥"
format = ' $symbol $branch '

[git_status]
format = '($all_status$ahead_behind )'

[golang]
symbol = "î˜§ "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[jobs]
symbol = "ğŸ"
format = " ($number )$symbol "
symbol_threshold = 1

[julia]
symbol = "î˜¤ "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%-I:%m%P" # Hour:Minute Format
format = '$time'
